### PR TITLE
Server crash

### LINKED ISSUE #97: blobby-server crashes
**I observed crashes of the blobby-server during endurance test. The server crashes with the following error:**
...
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 385h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 386h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:56:10 DKBlobbyServer blobby-server[932]: New incoming connection from 138.37.14.89:51577, 1 clients connected now
Feb 09 13:56:10 DKBlobbyServer blobby-server[932]: Connection 138.37.14.89:51577 closed via 26, 0 clients connected now
Feb 09 13:56:17 DKBlobbyServer blobby-server[932]: New incoming connection from 138.37.14.89:61799, 1 clients connected now
Feb 09 13:56:17 DKBlobbyServer blobby-server[932]: New player "ROFLCOPTER" connected from 138.37.14.89:61799
Feb 09 13:58:20 DKBlobbyServer blobby-server[932]: New incoming connection from 60.122.140.79:32072, 2 clients connected now
Feb 09 13:58:20 DKBlobbyServer blobby-server[932]: Connection 60.122.140.79:32072 closed via 26, 1 clients connected now
Feb 09 13:58:29 DKBlobbyServer blobby-server[932]: New incoming connection from 60.122.140.79:31462, 2 clients connected now
Feb 09 13:58:29 DKBlobbyServer blobby-server[932]: New player "IronFist" connected from 60.122.140.79:31462
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 387h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 388h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 389h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 390h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 391h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 392h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 393h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 394h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 395h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 396h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 397h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 398h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 399h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 400h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 390h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 391h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 392h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 393h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 394h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 395h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 396h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 397h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 398h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 399h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 400h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 378h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 379h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 380h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 381h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 382h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 383h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 384h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 385h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 386h running
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 08 21:21:59 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:56:10 DKBlobbyServer blobby-server[932]: New incoming connection from 138.37.14.89:51577, 1 clients connected now
Feb 09 13:56:10 DKBlobbyServer blobby-server[932]: Connection 138.37.14.89:51577 closed via 26, 0 clients connected now
Feb 09 13:56:17 DKBlobbyServer blobby-server[932]: New incoming connection from 138.37.14.89:61799, 1 clients connected now
Feb 09 13:56:17 DKBlobbyServer blobby-server[932]: New player "ROFLCOPTER" connected from 138.37.14.89:61799
Feb 09 13:58:20 DKBlobbyServer blobby-server[932]: New incoming connection from 60.122.140.79:32072, 2 clients connected now
Feb 09 13:58:20 DKBlobbyServer blobby-server[932]: Connection 60.122.140.79:32072 closed via 26, 1 clients connected now
Feb 09 13:58:29 DKBlobbyServer blobby-server[932]: New incoming connection from 60.122.140.79:31462, 2 clients connected now
Feb 09 13:58:29 DKBlobbyServer blobby-server[932]: New player "IronFist" connected from 60.122.140.79:31462
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 387h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 388h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 389h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 390h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 391h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 392h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 393h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 394h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 395h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 396h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 397h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 398h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 399h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 400h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 401h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 402h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Blobby Server Status Report 403h running
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  packet count: 227593
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  accepted connections: 261
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  started games: 16
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]:  game steps: 117191
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: loaded rules BV2 Default Rules by Blobby Volley 2 Developers from default.lua
Feb 09 13:58:43 DKBlobbyServer blobby-server[932]: Created game "IronFist" vs. "ROFLCOPTER", rules:default.lua
Feb 09 14:00:03 DKBlobbyServer blobby-server[932]: Disconnected player ROFLCOPTER
Feb 09 14:00:03 DKBlobbyServer blobby-server[932]: Connection 138.37.14.89:61799 closed via 26, 1 clients connected now
Feb 09 14:00:03 DKBlobbyServer blobby-server[932]: Removed game 60.122.140.79:31462 vs 138.37.14.89:61799 from gamelist
Feb 09 14:00:06 DKBlobbyServer blobby-server[932]: Disconnected player IronFist
Feb 09 14:00:06 DKBlobbyServer blobby-server[932]: Connection 60.122.140.79:31462 closed via 26, 0 clients connected now
Feb 09 14:00:14 DKBlobbyServer blobby-server[932]: New incoming connection from 138.37.14.89:54538, 1 clients connected now
Feb 09 14:00:14 DKBlobbyServer blobby-server[932]: Connection 138.37.14.89:54538 closed via 26, 0 clients connected now
Feb 09 14:00:17 DKBlobbyServer blobby-server[932]: New incoming connection from 60.122.140.79:31692, 1 clients connected now
Feb 09 14:00:17 DKBlobbyServer blobby-server[932]: Connection 60.122.140.79:31692 closed via 26, 0 clients connected now
Feb 09 14:00:21 DKBlobbyServer blobby-server[932]: New incoming connection from 138.37.14.89:64319, 1 clients connected now
Feb 09 14:00:21 DKBlobbyServer blobby-server[932]: New player "ROFLCOPTER" connected from 138.37.14.89:64319
Feb 09 14:00:28 DKBlobbyServer blobby-server[932]: New incoming connection from 60.122.140.79:31248, 2 clients connected now
Feb 09 14:00:28 DKBlobbyServer blobby-server[932]: New player "IronFist" connected from 60.122.140.79:31248
Feb 09 14:00:55 DKBlobbyServer blobby-server[932]: loaded rules BV2 Default Rules by Blobby Volley 2 Developers from default.lua
Feb 09 14:00:55 DKBlobbyServer blobby-server[932]: Created game "IronFist" vs. "ROFLCOPTER", rules:default.lua
Feb 09 14:00:55 DKBlobbyServer blobby-server[932]: blobby-server: /home/bvuser/bv2_cpp_server/src/server/MatchMaker.cpp:218: void MatchMaker::startGame(PlayerID, PlayerID): Assertion `first != mPlayerMap.end()' failed.

### PR DESCRIPTION
**Pull request by ngc92**
I think these changes will fix #97.  There might still be other lurking problems, though.

I've implemented the following:
 1) Server keeps track of who has opened and closed a connection, and discards any packets that come in from an already closed connection.
 2) If a lobby packet comes in and the sending player is not actually in the lobby (i.e. known to the MatchMaker), then we drop this packet.
 3) Processing of our game messages happens in a try-catch block, so if one message causes something to go wrong, we won't crash the entire server. There is the question of what state the server is in after an exception, tough... silently running in a broken state is probably not helpful. Maybe we should disconnect the player with the offending packet, to make sure at least that gets a full reset.
 4) I've changed the asserts that caused the crash in #97 to throws instead. With 3), this should now not cause a crash.

### CODE REVIEW

**Comment by danielknobe** [comment]
Nice change! This will hopefully fix (most of) the problem. After merge I will update the beta server to get it checked by community.

File: src/server/DedicatedServer.cpp [hunk 1]
```diff
@@ -187,63 +200,29 @@ void DedicatedServer::processPackets()
...
-				break;
-			}
+				try {
+					RakNet::BitStream stream(packet->data, packet->length, false);
+					stream.IgnoreBytes(1);	// ignore the message id
+					processSingleMessage(static_cast<MessageType>(packet_id), packet->playerId, stream);
+				} catch (const std::exception& error) {
+					syslog(LOG_ERR, "An error occurred while processing packet (%d) from %s: %s",
+						   packet_id, packet->playerId.toString().c_str(), error.what());
+				}
```
Comment (danielknobe) [inline src/server/DedicatedServer.cpp:222]: Missing break

File: src/server/DedicatedServer.cpp [hunk 2]
```diff
@@ -342,20 +321,16 @@ void DedicatedServer::printAllGames(std::ostream& stream) const
...
 	// If the client knows nothing about versioning, the version is 0.0
 	int major = 0;
 	int minor = 0;
 	bool wrongPackageSize = true;
 
-	// current client has bitSize 72
-
-	if( stream.GetNumberOfBitsUsed() == 72)
+	// current client has bitSize 64
+	if( stream.GetNumberOfBitsUsed() == 64)
```
[the remark this answers is not in the document]
Comment (ngc92) [reply src/server/DedicatedServer.cpp:332]: because further up the call chain,
```
RakNet::BitStream stream(packet->data, packet->length, false);
stream.IgnoreBytes(1);	// ignore the message id
processSingleMessage(static_cast<MessageType>(packet_id), packet->playerId, stream);
```
the message id byte is ignored now, but now that I look at this again it seems wrong. I guess I was thinking of number of bits left.

File: src/server/DedicatedServer.cpp (hunk 1 above)
Comment (ngc92) [reply src/server/DedicatedServer.cpp:222]: good catch

Comment (ngc92) [reply src/server/DedicatedServer.cpp:222]: one question is still, should we disconnect the player that caused the exception in the first case. To make sure that this player's connection is not in some weird, undefined state.

Comment (danielknobe) [reply src/server/DedicatedServer.cpp:222]: I'm not sure. In future cases this can be an overreaction.
